[package]
name = "watcherd"
version = "0.1.0"
authors = ["Anton Barkovsky <anton@swarmer.me>"]

[dependencies]
rustc-serialize = "0.3"
docopt = "0.6"
serde = "0.8"
serde_json = "0.8"
nix = "0.6.0"
log = "0.3.6"
env_logger = "0.3.4"
